### ISSUE TITLE
downloadOnly

### ISSUE THREAD

**Issue by bktoky** [stevenMieMie/subsampling-scale-image-view-demo#1]
Glide.with(getActivity())
                                                    .load(url).downloadOnly(new SimpleTarget<File>() {
                                                @Override
                                                public void onResourceReady(File resource, GlideAnimation<? super File> glideAnimation) {
                                                    mSubsamplingScaleImageView.setImage(ImageSource.uri(Uri.fromFile(resource)));
                                                }});

**Comment by stevenMieMie** [comment]
嗯 重新把Glide的使用看了一遍，谢谢
